// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1NLahqWJ8glLgK9jGKfuvu90X562eiw',
    appId: '1:445812609870:web:9271121e2736f520d2c41f',
    messagingSenderId: '445812609870',
    projectId: 'tenacious-veld-426502-c3',
    authDomain: 'tenacious-veld-426502-c3.firebaseapp.com',
    storageBucket: 'tenacious-veld-426502-c3.firebasestorage.app',
    measurementId: 'G-SZEERM6277',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdT1wFs8mkLKbTQOZS7uFUc5nrH0TVcrA',
    appId: '1:445812609870:android:d84da5994882ff97d2c41f',
    messagingSenderId: '445812609870',
    projectId: 'tenacious-veld-426502-c3',
    storageBucket: 'tenacious-veld-426502-c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdxgibOVqTG862DJ1quLbyIqptidmOyjI',
    appId: '1:445812609870:ios:b7e0ab849be0d15cd2c41f',
    messagingSenderId: '445812609870',
    projectId: 'tenacious-veld-426502-c3',
    storageBucket: 'tenacious-veld-426502-c3.firebasestorage.app',
    iosClientId: '445812609870-j5avdmiqpobg5i2n6kndvde4b50eim5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.lost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdxgibOVqTG862DJ1quLbyIqptidmOyjI',
    appId: '1:445812609870:ios:b7e0ab849be0d15cd2c41f',
    messagingSenderId: '445812609870',
    projectId: 'tenacious-veld-426502-c3',
    storageBucket: 'tenacious-veld-426502-c3.firebasestorage.app',
    iosClientId: '445812609870-j5avdmiqpobg5i2n6kndvde4b50eim5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.lost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc1NLahqWJ8glLgK9jGKfuvu90X562eiw',
    appId: '1:445812609870:web:10371ae00c5d71a9d2c41f',
    messagingSenderId: '445812609870',
    projectId: 'tenacious-veld-426502-c3',
    authDomain: 'tenacious-veld-426502-c3.firebaseapp.com',
    storageBucket: 'tenacious-veld-426502-c3.firebasestorage.app',
    measurementId: 'G-HHXTN4Q8J3',
  );
}
